# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [12]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [13]:
print(np.version.full_version)

2.4.1


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [18]:
a = np.random.rand(2, 3, 5)


[[[0.32546411 0.37136039 0.05263585 0.88363809 0.37877624]
  [0.70235141 0.51090719 0.93345349 0.31392738 0.48636335]
  [0.81290339 0.04547231 0.17033079 0.4378963  0.92376413]]

 [[0.34524613 0.87716424 0.840821   0.95072144 0.67827017]
  [0.09983372 0.62815426 0.92154599 0.90856916 0.50475024]
  [0.80869811 0.91326593 0.11810986 0.64601474 0.85998931]]]



### 4. Print a.


In [19]:
print(a)


[[[0.32546411 0.37136039 0.05263585 0.88363809 0.37877624]
  [0.70235141 0.51090719 0.93345349 0.31392738 0.48636335]
  [0.81290339 0.04547231 0.17033079 0.4378963  0.92376413]]

 [[0.34524613 0.87716424 0.840821   0.95072144 0.67827017]
  [0.09983372 0.62815426 0.92154599 0.90856916 0.50475024]
  [0.80869811 0.91326593 0.11810986 0.64601474 0.85998931]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [20]:
b = np.random.rand(5, 2, 3)


### 6. Print b.


In [21]:
print(b)


[[[0.82730848 0.41872155 0.30179113]
  [0.90794957 0.57971374 0.4379869 ]]

 [[0.55960261 0.7192824  0.18374485]
  [0.11289777 0.94152314 0.38771332]]

 [[0.62815814 0.09976587 0.59619479]
  [0.08334061 0.40045244 0.62367452]]

 [[0.25718167 0.5560874  0.00905191]
  [0.13158486 0.11393549 0.68263723]]

 [[0.80590484 0.33834037 0.63648884]
  [0.32459592 0.15253683 0.02633195]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [24]:
same_size = a.shape == b.shape
print(same_size)

False



### 8. Are you able to add a and b? Why or why not?


In [30]:
# No, a and b cannot be added because they do not have the same shape.

#Error: ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [35]:
c = np.transpose(b, (1, 2, 0))
print(c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [36]:
d = a + c
print(d)

[[[1.1527726  0.930963   0.68079399 1.14081976 1.18468108]
  [1.12107297 1.2301896  1.03321935 0.87001478 0.82470372]
  [1.11469451 0.22921716 0.76652558 0.4469482  1.56025297]]

 [[1.25319571 0.99006201 0.92416161 1.0823063  1.00286609]
  [0.67954747 1.56967739 1.32199844 1.02250464 0.65728707]
  [1.24668501 1.30097925 0.74178439 1.32865197 0.88632127]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [38]:
print(a) # the range of numbers is between 0 - 1

print(d) # the range of number is between 0.3 - 1.5


[[[0.32546411 0.37136039 0.05263585 0.88363809 0.37877624]
  [0.70235141 0.51090719 0.93345349 0.31392738 0.48636335]
  [0.81290339 0.04547231 0.17033079 0.4378963  0.92376413]]

 [[0.34524613 0.87716424 0.840821   0.95072144 0.67827017]
  [0.09983372 0.62815426 0.92154599 0.90856916 0.50475024]
  [0.80869811 0.91326593 0.11810986 0.64601474 0.85998931]]]
[[[1.1527726  0.930963   0.68079399 1.14081976 1.18468108]
  [1.12107297 1.2301896  1.03321935 0.87001478 0.82470372]
  [1.11469451 0.22921716 0.76652558 0.4469482  1.56025297]]

 [[1.25319571 0.99006201 0.92416161 1.0823063  1.00286609]
  [0.67954747 1.56967739 1.32199844 1.02250464 0.65728707]
  [1.24668501 1.30097925 0.74178439 1.32865197 0.88632127]]]



### 12. Multiply a and c. Assign the result to e.


In [40]:
e = a * c
print(e)


[[[8.76342138e-02 7.71739781e-02 1.74033292e-03 2.00811633e-01
   1.15624329e-01]
  [2.06554299e-01 1.87751524e-01 8.69295320e-02 5.48026354e-02
   8.00341793e-02]
  [1.99427173e-01 3.79934861e-04 1.72971475e-02 1.73573179e-03
   5.43141493e-01]]

 [[1.08222952e-01 8.68654761e-02 5.89201401e-02 1.18935775e-01
   1.49330491e-01]
  [5.77787495e-03 3.71504099e-01 3.40083043e-01 9.40535081e-02
   3.88622361e-02]
  [2.86440208e-01 3.23374104e-01 8.70022187e-03 2.84888439e-01
   1.94746286e-02]]]




### 13. Does e equal to a? Why or why not?


In [31]:
# no the 'e' values are far higher than a. the shape is also different.





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [45]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f'd Max value is: {d_max}, d min value is: {d_min}, d mean value is: {d_mean}')

d Max value is: 1.569677392481292, d min value is: 0.22921715690519462, d mean value is: 1.0098299291722086



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [49]:
f = np.empty((2,3,5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [53]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]

            if value == d_min:
                f[i, j, k] = 0
            elif value == d_mean:
                f[i, j, k] = 50
            elif value == d_max:
                f[i, j, k] = 100
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

print(f)

[[[ 75.  25.  25.  75.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 75.   0.  25.  25.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25. 100.  75.  75.  25.]
  [ 75.  75.  25.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [58]:
print(d)
print("------------------------------------------------------------")
print(f)
# the mapping logic I beleive is correct however the data is derived from d and not random.rand therefore some of the data is different.


[[[1.1527726  0.930963   0.68079399 1.14081976 1.18468108]
  [1.12107297 1.2301896  1.03321935 0.87001478 0.82470372]
  [1.11469451 0.22921716 0.76652558 0.4469482  1.56025297]]

 [[1.25319571 0.99006201 0.92416161 1.0823063  1.00286609]
  [0.67954747 1.56967739 1.32199844 1.02250464 0.65728707]
  [1.24668501 1.30097925 0.74178439 1.32865197 0.88632127]]]
------------------------------------------------------------
[[[ 75.  25.  25.  75.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 75.   0.  25.  25.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25. 100.  75.  75.  25.]
  [ 75.  75.  25.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [68]:
import string

letters = list(string.ascii_uppercase)

idx = 0
for i in range(len(f)):
    block = []
    for j in range(len(f[i])):
        row = []
        for k in range(len(f[i][j])):
            row.append(letters[idx])
        block.append(row)
        idx += 1 # Incrementing by 1 to get the next letter
    s.append(block)


print(s)




[[['A', 'A', 'A', 'A', 'A'], ['B', 'B', 'B', 'B', 'B'], ['C', 'C', 'C', 'C', 'C']], [['D', 'D', 'D', 'D', 'D'], ['E', 'E', 'E', 'E', 'E'], ['F', 'F', 'F', 'F', 'F']]]
